development:
  adapter: postgresql
  encoding: unicode
  database: Blackmailr_development
  pool: 5
  username: Blackmailr
  password: dontblackmailme

test:
  adapter: postgresql
  encoding: unicode
  database: Blackmailr_test
  pool: 5
  username: Blackmailr
  password: dontblackmailme

# Heroku generates a production configuration for PostgreSQL automatically
